version: '3'

services:
  db:
    container_name: db_server
    image: postgres
    env_file:
      - ./config/development.env
    networks:
      - main
  backend:
    container_name: django_server
    build: ./backend
    command: ["./scripts/start.sh"]
    env_file:
      - ./config/development.env
    volumes:
      - ./backend:/code
    depends_on:
      - db
    networks:
      - main
  frontend:
    container_name: angular_server
    build:
      context: ./frontend
    volumes:
      - ./frontend:/code:ro
    command: "npm start"
    ports:
      - "4200:4200"
    networks:
      - main
    depends_on:
      - backend
      - db
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx/
    networks:
      - main
networks:
  main:
    driver: bridge
