version: '3'

services:
  db:
    container_name: db_server
    image: postgres
    env_file:
      - ./config/development.env
    networks:
      - main
  web:
    container_name: django_server
    build: .
    command: ["./scripts/start.sh"]
    env_file:
      - ./config/development.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - main
networks:
  main:
