# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190612_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
